<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    //Async
//     含义
// ES2017 标准引入了 async 函数，使得异步操作变得更加方便。

// async 函数是什么？一句话，它就是 Generator 函数的语法糖。

// 前文有一个 Generator 函数，依次读取两个文件。

// const fs = require('fs');

// const readFile = function (fileName) {
//   return new Promise(function (resolve, reject) {
//     fs.readFile(fileName, function(error, data) {
//       if (error) return reject(error);
//       resolve(data);
//     });
//   });
// };

// const gen = function* () {
//   const f1 = yield readFile('/etc/fstab');
//   const f2 = yield readFile('/etc/shells');
//   console.log(f1.toString());
//   console.log(f2.toString());
// };
// 上面代码的函数gen可以写成async函数，就是下面这样。

// const asyncReadFile = async function () {
//   const f1 = await readFile('/etc/fstab');
//   const f2 = await readFile('/etc/shells');
//   console.log(f1.toString());
//   console.log(f2.toString());
// };
// 一比较就会发现，async函数就是将 Generator 函数的星号（*）替换成async，将yield替换成await，仅此而已。

// async函数对 Generator 函数的改进，体现在以下四点。
// （1）内置执行器。

// Generator 函数的执行必须靠执行器，所以才有了co模块，而async函数自带执行器。也就是说，async函数的执行，与普通函数一模一样，只要一行。

// asyncReadFile();
// 上面的代码调用了asyncReadFile函数，然后它就会自动执行，输出最后结果。这完全不像 Generator 函数，需要调用next方法，或者用co模块，才能真正执行，得到最后结果。

// （2）更好的语义。

// async和await，比起星号和yield，语义更清楚了。async表示函数里有异步操作，await表示紧跟在后面的表达式需要等待结果。

// （3）更广的适用性。

// co模块约定，yield命令后面只能是 Thunk 函数或 Promise 对象，而async函数的await命令后面，可以是 Promise 对象和原始类型的值（数值、字符串和布尔值，但这时会自动转成立即 resolved 的 Promise 对象）。

// （4）返回值是 Promise。

// async函数的返回值是 Promise 对象，这比 Generator 函数的返回值是 Iterator 对象方便多了。你可以用then方法指定下一步的操作。

// 进一步说，async函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而await命令就是内部then命令的语法糖。

// 基本用法
// async函数返回一个 Promise 对象，可以使用then方法添加回调函数。当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。

// 下面是一个例子。

// async function getStockPriceByName(name) {
//   const symbol = await getStockSymbol(name);
//   const stockPrice = await getStockPrice(symbol);
//   return stockPrice;
// }

// getStockPriceByName('goog').then(function (result) {
//   console.log(result);
// });
// 上面代码是一个获取股票报价的函数，函数前面的async关键字，表明该函数内部有异步操作。调用该函数时，会立即返回一个Promise对象。

// 下面是另一个例子，指定多少毫秒后输出一个值。

// function timeout(ms) {
//   return new Promise((resolve) => {
//     setTimeout(resolve, ms);
//   });
// }

// async function asyncPrint(value, ms) {
//   await timeout(ms);
//   console.log(value);
// }

// asyncPrint('hello world', 50);
// 上面代码指定 50 毫秒以后，输出hello world。
// async 函数有多种使用形式。

// // 函数声明
// async function foo() {}

// // 函数表达式
// const foo = async function () {};

// // 对象的方法
// let obj = { async foo() {} };
// obj.foo().then(...)

// // Class 的方法
// class Storage {
//   constructor() {
//     this.cachePromise = caches.open('avatars');
//   }

//   async getAvatar(name) {
//     const cache = await this.cachePromise;
//     return cache.match(`/avatars/${name}.jpg`);
//   }
// }

// const storage = new Storage();
// storage.getAvatar('jake').then(…);

// // 箭头函数
// const foo = async () => {};


// 语法
// async函数的语法规则总体上比较简单，难点是错误处理机制。

// 返回 Promise 对象
// async函数返回一个 Promise 对象。

// async函数内部return语句返回的值，会成为then方法回调函数的参数。

// async function f() {
//   return 'hello world';
// }

// f().then(v => console.log(v))
// // "hello world"
// 上面代码中，函数f内部return命令返回的值，会被then方法回调函数接收到。

// async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。

// async function f() {
//   throw new Error('出错了');
// }

// f().then(
//   v => console.log(v),
//   e => console.log(e)
// )
// // Error: 出错了

// Promise 对象的状态变化
// async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。

// 下面是一个例子。

// async function getTitle(url) {
//   let response = await fetch(url);
//   let html = await response.text();
//   return html.match(/<title>([\s\S]+)<\/title>/i)[1];
// }
// getTitle('https://tc39.github.io/ecma262/').then(console.log)
// // "ECMAScript 2017 Language Specification"
// 上面代码中，函数getTitle内部有三个操作：抓取网页、取出文本、匹配页面标题。只有这三个操作全部完成，才会执行then方法里面的console.log。

// await 命令
// 正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。

// async function f() {
//   // 等同于
//   // return 123;
//   return await 123;
// }

// f().then(v => console.log(v))
// // 123
// 上面代码中，await命令的参数是数值123，这时等同于return 123。

// 另一种情况是，await命令后面是一个thenable对象（即定义then方法的对象），那么await会将其等同于 Promise 对象。

// class Sleep {
//   constructor(timeout) {
//     this.timeout = timeout;
//   }
//   then(resolve, reject) {
//     const startTime = Date.now();
//     setTimeout(
//       () => resolve(Date.now() - startTime),
//       this.timeout
//     );
//   }
// }

// (async () => {
//   const sleepTime = await new Sleep(1000);
//   console.log(sleepTime);
// })();
// // 1000
// 上面代码中，await命令后面是一个Sleep对象的实例。这个实例不是 Promise 对象，但是因为定义了then方法，await会将其视为Promise处理。

// 这个例子还演示了如何实现休眠效果。JavaScript 一直没有休眠的语法，但是借助await命令就可以让程序停顿指定的时间。下面给出了一个简化的sleep实现。

// function sleep(interval) {
//   return new Promise(resolve => {
//     setTimeout(resolve, interval);
//   })
// }

// // 用法
// async function one2FiveInAsync() {
//   for(let i = 1; i <= 5; i++) {
//     console.log(i);
//     await sleep(1000);
//   }
// }

// one2FiveInAsync();
// await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。

// async function f() {
//   await Promise.reject('出错了');
// }

// f()
// .then(v => console.log(v))
// .catch(e => console.log(e))
// // 出错了
// 注意，上面代码中，await语句前面没有return，但是reject方法的参数依然传入了catch方法的回调函数。这里如果在await前面加上return，效果是一样的。

// 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。

// async function f() {
//   await Promise.reject('出错了');
//   await Promise.resolve('hello world'); // 不会执行
// }
// 上面代码中，第二个await语句是不会执行的，因为第一个await语句状态变成了reject。

// 有时，我们希望即使前一个异步操作失败，也不要中断后面的异步操作。这时可以将第一个await放在try...catch结构里面，这样不管这个异步操作是否成功，第二个await都会执行。

// async function f() {
//   try {
//     await Promise.reject('出错了');
//   } catch(e) {
//   }
//   return await Promise.resolve('hello world');
// }

// f()
// .then(v => console.log(v))
// // hello world
// 另一种方法是await后面的 Promise 对象再跟一个catch方法，处理前面可能出现的错误。

// async function f() {
//   await Promise.reject('出错了')
//     .catch(e => console.log(e));
//   return await Promise.resolve('hello world');
// }

// f()
// .then(v => console.log(v))
// // 出错了
// // hello world

// 顶层 await
// 根据语法规格，await命令只能出现在 async 函数内部，否则都会报错。

// // 报错
// const data = await fetch('https://api.example.com');
// 上面代码中，await命令独立使用，没有放在 async 函数里面，就会报错。

// 目前，有一个语法提案，允许在模块的顶层独立使用await命令。这个提案的目的，是借用await解决模块异步加载的问题。

// // awaiting.js
// let output;
// async function main() {
//   const dynamic = await import(someMission);
//   const data = await fetch(url);
//   output = someProcess(dynamic.default, data);
// }
// main();
// export { output };
// 上面代码中，模块awaiting.js的输出值output，取决于异步操作。我们把异步操作包装在一个 async 函数里面，然后调用这个函数，只有等里面的异步操作都执行，变量output才会有值，否则就返回undefined。

// 上面的代码也可以写成立即执行函数的形式。

// // awaiting.js
// let output;
// (async function main() {
//   const dynamic = await import(someMission);
//   const data = await fetch(url);
//   output = someProcess(dynamic.default, data);
// })();
// export { output };
// 下面是加载这个模块的写法。

// // usage.js
// import { output } from "./awaiting.js";

// function outputPlusValue(value) { return output + value }

// console.log(outputPlusValue(100));
// setTimeout(() => console.log(outputPlusValue(100), 1000);
// 上面代码中，outputPlusValue()的执行结果，完全取决于执行的时间。如果awaiting.js里面的异步操作没执行完，加载进来的output的值就是undefined。

// 目前的解决方法，就是让原始模块输出一个 Promise 对象，从这个 Promise 对象判断异步操作有没有结束。

// // awaiting.js
// let output;
// export default (async function main() {
//   const dynamic = await import(someMission);
//   const data = await fetch(url);
//   output = someProcess(dynamic.default, data);
// })();
// export { output };
// 上面代码中，awaiting.js除了输出output，还默认输出一个 Promise 对象（async 函数立即执行后，返回一个 Promise 对象），从这个对象判断异步操作是否结束。

// 下面是加载这个模块的新的写法。

// // usage.js
// import promise, { output } from "./awaiting.js";

// function outputPlusValue(value) { return output + value }

// promise.then(() => {
//   console.log(outputPlusValue(100));
//   setTimeout(() => console.log(outputPlusValue(100), 1000);
// });
// 上面代码中，将awaiting.js对象的输出，放在promise.then()里面，这样就能保证异步操作完成以后，才去读取output。

// 这种写法比较麻烦，等于要求模块的使用者遵守一个额外的使用协议，按照特殊的方法使用这个模块。一旦你忘了要用 Promise 加载，只使用正常的加载方法，依赖这个模块的代码就可能出错。而且，如果上面的usage.js又有对外的输出，等于这个依赖链的所有模块都要使用 Promise 加载。

// 顶层的await命令，就是为了解决这个问题。它保证只有异步操作完成，模块才会输出值。

// // awaiting.js
// const dynamic = import(someMission);
// const data = fetch(url);
// export const output = someProcess((await dynamic).default, await data);
// 上面代码中，两个异步操作在输出的时候，都加上了await命令。只有等到异步操作完成，这个模块才会输出值。

// 加载这个模块的写法如下。

// // usage.js
// import { output } from "./awaiting.js";
// function outputPlusValue(value) { return output + value }

// console.log(outputPlusValue(100));
// setTimeout(() => console.log(outputPlusValue(100), 1000);
// 上面代码的写法，与普通的模块加载完全一样。也就是说，模块的使用者完全不用关心，依赖模块的内部有没有异步操作，正常加载即可。

// 这时，模块的加载会等待依赖模块（上例是awaiting.js）的异步操作完成，才执行后面的代码，有点像暂停在那里。所以，它总是会得到正确的output，不会因为加载时机的不同，而得到不一样的值。

// 下面是顶层await的一些使用场景。

// // import() 方法加载
// const strings = await import(`/i18n/${navigator.language}`);

// // 数据库操作
// const connection = await dbConnector();

// // 依赖回滚
// let jQuery;
// try {
//   jQuery = await import('https://cdn-a.com/jQuery');
// } catch {
//   jQuery = await import('https://cdn-b.com/jQuery');
// }
// 注意，如果加载多个包含顶层await命令的模块，加载命令是同步执行的。

// // x.js
// console.log("X1");
// await new Promise(r => setTimeout(r, 1000));
// console.log("X2");

// // y.js
// console.log("Y");

// // z.js
// import "./x.js";
// import "./y.js";
// console.log("Z");
// 上面代码有三个模块，最后的z.js加载x.js和y.js，打印结果是X1、Y、X2、Z。这说明，z.js并没有等待x.js加载完成，再去加载y.js。

// 顶层的await命令有点像，交出代码的执行权给其他的模块加载，等异步操作完成后，再拿回执行权，继续向下执行。


</script>
</html>